/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.CAdd_Vehicle;
import controller.CBooking;
import java.awt.Image;
import java.io.File;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import datetimepicker.DatePicker;
import java.awt.event.KeyEvent;
import java.io.BufferedInputStream;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author prade
 */
public class VAdd_Vehicle_Form extends javax.swing.JFrame {

    /**
     * Creates new form Add_Vehicle_Form
     */
    
    public VAdd_Vehicle_Form() {
        initComponents();
        this.pack();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel7 = new javax.swing.JLabel();
        txt_vmodel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmb_vtype = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txt_overdueprice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmb_noofseats = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cmb_fueltype = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        txt_numplate = new javax.swing.JTextField();
        txt_priceperday = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_kmperliter = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1182, 730));
        setSize(new java.awt.Dimension(1182, 730));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel7.setText("Model Name");

        txt_vmodel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_vmodel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vmodelActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setText("Vehicle Number Plate");

        cmb_vtype.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cmb_vtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car", "MiniVan", "Van" }));
        cmb_vtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_vtypeActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setText("Vehicle Type");

        txt_overdueprice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_overdueprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_overduepriceActionPerformed(evt);
            }
        });
        txt_overdueprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_overduepriceKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("Select Number of Seats");

        cmb_noofseats.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cmb_noofseats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "4", "5" }));
        cmb_noofseats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_noofseatsActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setText("Fuel type");

        cmb_fueltype.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cmb_fueltype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Petrol", "Diesel" }));
        cmb_fueltype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_fueltypeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Select Vehicle Pricing");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Vehcile Details");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11.setText("Overdue Price");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel13.setText("Price Per Day");

        btn_clear.setBackground(new java.awt.Color(255, 51, 51));
        btn_clear.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_clear.setText("CLEAR");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_add.setBackground(new java.awt.Color(0, 153, 204));
        btn_add.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        txt_numplate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_numplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numplateActionPerformed(evt);
            }
        });
        txt_numplate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_numplateKeyPressed(evt);
            }
        });

        txt_priceperday.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_priceperday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_priceperdayActionPerformed(evt);
            }
        });
        txt_priceperday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_priceperdayKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel14.setText("Km Per Liter");

        txt_kmperliter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_kmperliter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_kmperliterKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add a Vehicle");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fleet.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(425, 425, 425))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(77, 77, 77))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(570, 570, 570)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14)
                            .addComponent(jLabel10))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_priceperday, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmb_fueltype, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_kmperliter, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_numplate, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(452, 452, 452))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(720, 720, 720)
                        .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(599, 599, 599)
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_overdueprice, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(cmb_vtype, 0, 212, Short.MAX_VALUE)
                            .addComponent(txt_vmodel)
                            .addComponent(cmb_noofseats, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_numplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(cmb_vtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txt_kmperliter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_noofseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmb_fueltype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_vmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_priceperday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txt_overdueprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_vtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_vtypeActionPerformed
        // Get the selected type from cmb_type
        String selectedType = (String) cmb_vtype.getSelectedItem();

        // Update cmb_noofseats options based on the selected type
        updateNoOfSeatsOptions(selectedType);
    }//GEN-LAST:event_cmb_vtypeActionPerformed

    private void cmb_noofseatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_noofseatsActionPerformed

    }//GEN-LAST:event_cmb_noofseatsActionPerformed

    private void cmb_fueltypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_fueltypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_fueltypeActionPerformed

    private void txt_overduepriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_overduepriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_overduepriceActionPerformed
    
    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        txt_numplate.setText("");
        txt_kmperliter.setText("");
        cmb_vtype.setSelectedIndex(0);
        cmb_noofseats.setSelectedIndex(0);
        cmb_fueltype.setSelectedIndex(0);
        txt_vmodel.setText("");
        txt_priceperday.setText("");
        txt_overdueprice.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private static String generateNextId(String lastId) {
        int nextNumber = 1;
        if (lastId != null && lastId.startsWith("V")) {
            int lastNumber = Integer.parseInt(lastId.substring(1));
            nextNumber = lastNumber + 1;
        }
        
        String formattedNumber = String.format("%03d", nextNumber);
        return "V" + formattedNumber;
    }
    
    private String generateLastID()
    {
        String lastId = null;
        try
        {
            ResultSet resultSet;
            CAdd_Vehicle c2 = new CAdd_Vehicle();
            resultSet = c2.getVehicleDetails();
            
            if (resultSet.next()) {
                lastId = resultSet.getString(1);
            }

        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        return lastId;
    }
    
    private boolean isValidNumberPlate(String numberPlate) {
        String regex = "^[A-Za-z0-9]{1,3}-[0-9]{4}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(numberPlate);
        return matcher.matches();
    }

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        if(txt_numplate.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Number Plate of the vehcile","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if (!isValidNumberPlate(txt_numplate.getText()))
        {
            JOptionPane.showMessageDialog(null,"Please Enter a Valid Number Plate","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if(txt_kmperliter.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Number of kilometers per liter of the vehcile","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if(txt_vmodel.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Number of kilometers per liter of the vehcile","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
        else if(txt_priceperday.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Daily price for the vehcile","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else if(txt_overdueprice.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Overdue price for the vehcile","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try
            {
            String vid,num_plate,vtype,fueltype,model;
            Double kmperlit,priceday,overduep;
            int noofseats;
            vid = generateNextId(generateLastID());
            num_plate = txt_numplate.getText();
            vtype = (String) cmb_vtype.getSelectedItem();
            kmperlit = Double.parseDouble(txt_kmperliter.getText());
            noofseats = Integer.parseInt((String) cmb_noofseats.getSelectedItem());
            fueltype = (String) cmb_fueltype.getSelectedItem();
            model = txt_vmodel.getText();
            
            priceday = Double.parseDouble(txt_priceperday.getText());
            overduep = Double.parseDouble(txt_overdueprice.getText());
            
            
            CAdd_Vehicle c1 = new CAdd_Vehicle();
            c1.addVehicle(vid, num_plate, vtype, model, noofseats, kmperlit, fueltype, 1, priceday, overduep);

            }
            catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error reading image file", "Error", JOptionPane.ERROR_MESSAGE);
    }
            
        }
        
        
    }//GEN-LAST:event_btn_addActionPerformed

    private void txt_numplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numplateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numplateActionPerformed

    private void txt_priceperdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_priceperdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_priceperdayActionPerformed

    private void txt_vmodelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vmodelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vmodelActionPerformed

    private void txt_kmperliterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_kmperliterKeyPressed
        String value = txt_kmperliter.getText();
        char inputChar = evt.getKeyChar();

        if ((inputChar >= '0' && inputChar <= '9') || inputChar == '.' || inputChar == KeyEvent.VK_BACK_SPACE) {
            txt_kmperliter.setEditable(true);
        } else {
            txt_kmperliter.setEditable(false);
        }
    }//GEN-LAST:event_txt_kmperliterKeyPressed

    private void txt_priceperdayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_priceperdayKeyPressed
        // txt_priceperday
        String value = txt_priceperday.getText();
        char inputChar = evt.getKeyChar();

        if ((inputChar >= '0' && inputChar <= '9') || inputChar == '.' || inputChar == KeyEvent.VK_BACK_SPACE) {
            txt_priceperday.setEditable(true);
        } else {
            txt_priceperday.setEditable(false);
        }
    }//GEN-LAST:event_txt_priceperdayKeyPressed

    private void txt_overduepriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_overduepriceKeyPressed
        // txt_overdueprice
        String value = txt_overdueprice.getText();
        char inputChar = evt.getKeyChar();

        if ((inputChar >= '0' && inputChar <= '9') || inputChar == '.' || inputChar == KeyEvent.VK_BACK_SPACE) {
            txt_overdueprice.setEditable(true);
        } else {
            txt_overdueprice.setEditable(false);
        }
    }//GEN-LAST:event_txt_overduepriceKeyPressed

    private void txt_numplateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_numplateKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numplateKeyPressed

    private void updateNoOfSeatsOptions(String selectedType) 
    {
        DefaultComboBoxModel<String> noOfSeatsModel = new DefaultComboBoxModel<>();

        if ("Car".equals(selectedType)) {
            // Add Car-specific options
            noOfSeatsModel.addElement("2");
            noOfSeatsModel.addElement("4");
            noOfSeatsModel.addElement("5");
        } else if ("MiniVan".equals(selectedType)) {
            // Add MiniVan-specific options
            noOfSeatsModel.addElement("5");
            noOfSeatsModel.addElement("6");
            noOfSeatsModel.addElement("7");
            noOfSeatsModel.addElement("8");
        } else if ("Van".equals(selectedType)) {
            // Add Van-specific options
            noOfSeatsModel.addElement("8");
            noOfSeatsModel.addElement("9");
            noOfSeatsModel.addElement("10");
            noOfSeatsModel.addElement("11");
            noOfSeatsModel.addElement("12");
        }
        // Set the updated model for cmb_noofseats
        cmb_noofseats.setModel(noOfSeatsModel);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAdd_Vehicle_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAdd_Vehicle_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAdd_Vehicle_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAdd_Vehicle_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAdd_Vehicle_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JComboBox<String> cmb_fueltype;
    private javax.swing.JComboBox<String> cmb_noofseats;
    private javax.swing.JComboBox<String> cmb_vtype;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_kmperliter;
    private javax.swing.JTextField txt_numplate;
    private javax.swing.JTextField txt_overdueprice;
    private javax.swing.JTextField txt_priceperday;
    private javax.swing.JTextField txt_vmodel;
    // End of variables declaration//GEN-END:variables
}
